name: dart_otp
description: dart_otp is a dart package to generate and verify one-time passwords.
version: 1.3.0
author: Gin <gin.lance.inside@hotmail.com>

homepage: https://github.com/BrunoMiguens/dart_otp

environment:
  sdk: ">=1.13.0 <3.0.0"

dependencies:
  base32: ^2.1.1
  crypto: ^3.0.1

dev_dependencies:
  test: ^1.16.0
  test_coverage: ^0.5.0
